### ISSUE TITLE
Proposing django-compressor

### ISSUE THREAD

**Issue by camilonova** [jazzband/roadies#111] opened 2018-10-01 18:58 UTC
https://github.com/django-compressor/django-compressor

**Comment by jezdez** [comment] 2018-10-08 07:44
Interesting, this is kind of coming full circle a bit :)

@diox @karyon What do you think about moving compressor into Jazzband?

**Comment by camilonova** [comment] 2018-10-08 14:50
Lets do that then. How can I help?

**Comment by jezdez** [comment] 2018-10-08 18:06
Let's wait for @karyon to agree first, @camilonova.

**Comment by karyon** [comment] 2018-10-09 17:49
i'm not strongly against it, but i have the feeling that it won't help anybody. Contributions from outside will likely be almost zero, and my own commitment will drop from the low level it is on now to almost zero as well. or am i unreasonably negative here?

**Comment by camilonova** [comment] 2018-10-11 17:17
At least if someone wants to work on it will be easier at jazzband than in here.

**Comment by camilonova** [comment] 2018-11-25 13:06
@karyon shall we do this?

**Comment by jezdez** [comment] 2019-02-07 19:08
@karyon From the limited experience with other projects there is a chance that new people get the chance to help maintain it. This is most helpful when new Django or Python releases require making updates to the internals. As a former maintainer of django-compressor I can relate to you concerns though. So no pressure :)

**Comment by camilonova** [comment] 2019-02-16 13:47
@jezdez how can we make it happen?

**Comment by jezdez** [comment] 2019-03-01 08:34
@camilonova Basically I'm not sure if @karyon is okay with the move, and since they are the effective maintainer at the moment I'd rather not go ahead without their consent.

@karyon Apologies for pinging you again, could you please let us know if it's a YAY or NAY from you?

If it's a NAY, what can we do to alleviate your concerns? (e.g. you would still be able to make releases to PyPI by being the project lead member)

**Comment by karyon** [comment] 2019-03-13 22:03
i've thought more about this, and I think I don't like the idea of essentially handing out the right to do anything (except pip releases perhaps) to everyone. e.g. low-quality PRs might be merged, and then it will still be or diox having the responsibility of cleaning that up or living with releasing that through pip. also there is the chance of abuse, e.g. through mass-altering issues. i'm glad that this hasn't happened to the existing jazzband projects yet but it seems there's no guarantee it won't happen and no contingency plan if it happens.
also i still don't really see the benefit. i'm not sure it's any relief for me because of the aforementioned. there might be a little lower mental barrier for contributing, but effectively when creating a PR you either have that reviewed and everything is as before, or you merge it by yourself and have merged unreviewed code. reviewing other peoples code is either easy, in which case it hasn't been a problem so far for myself to do it, or hard, in which case people unfamiliar with the codebase cannot effectively do it. i'm against handing out the rights to pip releases. participating in issue discussions doesn't need any privileges (except for closing). and that's about everything that needs to be done to maintain this project, so...

@diox in case you would strongly prefer the transfer (maybe it's a stress relief for you!), you can do it. in my mind you're still the more senior maintainer :) so i won't veto it, but from me personally it's a nay.

**Comment by diox** [comment] 2019-03-14 00:35
Those are good points. We can continue to deal with the (low) influx of contributions as we've done - If people want to help maintain it, answering issues, trying to reproduce people's problems, and pinging us when someone with more seniority on the project is needed is fine, no need for extra permissions to do that.

@karyon You're the more active maintainer and I fully trust your opinion on this, so I'm leaving the final decision to you.

**Comment by jezdez** [comment] 2019-03-14 15:35
@karyon Thank you for elaborating your concerns, I appreciate your patience for considering moving the project to Jazzband. I've commented on some points below since I feel I needed to try to alleviate some of the concerns.

> i've thought more about this, and I think I don't like the idea of essentially handing out the right to do anything (except pip releases perhaps) to everyone. e.g. low-quality PRs might be merged, and then it will still be or diox having the responsibility of cleaning that up or living with releasing that through pip. also there is the chance of abuse, e.g. through mass-altering issues. i'm glad that this hasn't happened to the existing jazzband projects yet but it seems there's no guarantee it won't happen and no contingency plan if it happens.

FTR, there are contingency plans for abuse, and just like any abuse on this platform it will need to be reported to GitHub. E.g. mass-edited issues for example can be reverted, issues can be locked and members can be banned, if needed. In that sense the project maintenance is not different to other projects, except that I'm also here to help solve such problems.

> also i still don't really see the benefit.

To be clear, that's fair, Jazzband is about making maintenance easier, not harder.

> i'm not sure it's any relief for me because of the aforementioned. there might be a little lower mental barrier for contributing, but effectively when creating a PR you either have that reviewed and everything is as before, or you merge it by yourself and have merged unreviewed code. reviewing other peoples code is either easy, in which case it hasn't been a problem so far for myself to do it, or hard, in which case people unfamiliar with the codebase cannot effectively do it.

Lowering the threshold to enable new people to do reviews, triage tickets and collaborate actively should not be underestimated as a way to have a long-term project health though. In that sense I encourage you to not think about how it is right now, but how things will look like in the mid- and long-term. I know that django-compressor wouldn't have survived if diox wouldn't have stepped up years ago, or you more recently. Jazzband is basically trying to make it a non-issue on-boarding new people.

> i'm against handing out the rights to pip releases.

Handing out rights to do pip release was never on the table. Jazzband does releases to its own repo (if configured to do so) and the project leads (e.g. @diox and you) still need to confirm them to push them to PyPI. Confirmation happens by way of emailing the project lead(s) and asking to review the changes, asking to press a button to trigger the upload to PyPI. This feature is entirely optional though.

> participating in issue discussions doesn't need any privileges (except for closing).

Ticket triage (e.g. assigning labels) is not possible for non-members, which as we all know is a big part of maintenance.

**Comment by jezdez** [comment] 2019-04-23 09:33
I'm closing this for now, since I feel like everything has been said. Thank you for your consideration, @diox and @karyon!

**Closed by jezdez** 2019-04-23 09:33 UTC
